# This file contains secrets for local development
# DO NOT commit this file to version control

# API Configuration
API_URL = "http://localhost:8000"

# OpenAI API Key
OPENAI_API_KEY = "your-api-key-here" 